config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :wines do
    member do
      get :restaurants
    end
  end

  resources :restaurants do
    resources :wines, controller: 'restaurants_wines'
  end

  root "home#index"
  

end

app/models/restaurant.rb
  class Restaurant < ActiveRecord::Base

  belongs_to :user

  has_many :offerings
  has_many :wines, through: :offerings

  geocoded_by :address
  after_validation :geocode

  validates :name, :cuisine, :address, :avatar, presence: {message: "must exist"}

  self.per_page = 20

  has_attached_file :avatar, styles: { :medium => "300x300>", :thumb => "100x100>" },
                     default_url: ActionController::Base.helpers.asset_path("missing_:style.png"),
                     storage: :s3,
                     s3_host_name: "s3-us-west-2.amazonaws.com",
                     :s3_credentials =>{:bucket => "winesearch", :access_key_id => ENV['s3_access_key_id'], :secret_access_key => ENV['s3_secret_key_id']}

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  crop_attached_file :avatar, aspect: "1:1"

  def s3_credentials
    {:bucket => "winesearch", :access_key_id => ENV['s3_access_key_id'], :secret_access_key => ENV['s3_secret_key_id']}
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  helper_method :sort_column, :sort_direction

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_restaurant, only: [:edit, :update, :show, :destroy]

  def new
    @restaurant = Restaurant.new
    @restaurant.wines.build
  end

  def create
    @restaurant = Restaurant.new restaurant_params
    @restaurant.user = current_user
    if @restaurant.save
      if params[:restaurant][:avatar]
        render :crop
      else
        redirect_to restaurant_path(@restaurant), notice: "Your restaurant was created!"
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update_attributes restaurant_params
      if params[:restaurant][:avatar]
        render :crop
      else
        redirect_to restaurant_path(@restaurant), notice: "Your restaurant was created!"
      end
    else
      render :edit
    end
  end

  def destroy
    if @restaurant.destroy
      redirect_to root_path
    else
      notice = "We had some difficulties deleting the restaurant. Please try again"
    end
  end

  def show
    @wine = @restaurant.wines.build
    @hash = Gmaps4rails.build_markers(@restaurant) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.json({ title: restaurant.name })
    end
  end

  def index
    @restaurants = Restaurant.paginate(:page => params[:page])
    @restaurants = @restaurants.order("#{sort_column} #{sort_direction}")
    if params[:search]
      @wines = Wine.search(params[:search]).order("created_at DESC").near([request.remote_ip, 20])
    else
      @wines = Wine.all.order("created_at DESC")
    end
    respond_to do |format|
      format.html
      format.js {render}
    end
  end


  def wines
    @wine = Wine.all
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name,
                                       :cuisine, 
                                       :address,
                                       :avatar_original_w, 
                                       :avatar_original_h, 
                                       :avatar_box_w,
                                       :avatar_crop_x,
                                       :avatar_crop_y,
                                       :avatar_crop_w, 
                                       :avatar_crop_h, 
                                       :avatar_aspect,
                                       :city,
                                       :avatar,
                                       {wine_ids: []},
                                       {wine_attributes: [:name, :kind, :origin, :serving_type, :id]})

  end


  def find_restaurant
    @restaurant = Restaurant.find params[:id]
  end

  def sort_column
    Restaurant.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

  def generate_map_json(restaurant)
    Gmaps4rails.build_markers(restaurant) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      link = link_to restaurant.title, restaurant_path(restaurant)
      marker.infowindow "#{restaurant.title}"
    end
  end
end

app/views/restaurants/_form.html.erb
<div class="container-fluid">

  <div id="restaurant-form" class="form-group col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2">
    <%= simple_form_for @restaurant do |f| %>
      <%= f.input :name, autofocus: true %>
      <%= f.input :cuisine %>
      <%= f.input :address %>
      <div class="center-block form-inputs">
        <%= f.association :wines,
        collection: Wine.all,
        include_blank: true,
        input_html: { class: 'chosen-select' } %>
      </div>
      <%= f.label :profile_picture %>
      <%= f.file_field :avatar %> 
      <br>
       <p>Your photo will appear in search results. We recommend choosing an image with the name or logo of your restauraunt</p>

      <br>
        <%= f.submit "Save", class: "btn btn-default pull-right" %>
      </div>
    <% end %>   
  </div>
</div>

<script type="text/javascript">
  (function(){jQuery(function(){return $("#restaurant_wine_ids").chosen()})}).call(this);
</script> 

app/views/restaurants/_page.html.erb
<% @restaurants.each do |r| %>
  <tr>
    <td><%= link_to r.name, restaurant_path(r) %></td>
    <td><%= r.address %></td>
    <td><%= r.cuisine %></td>
  </tr>
<% end %>
      </table>
<div class="text-center">
  <%= will_paginate @restaurants, :page_links => false %>
</div>
    </div>
  </div>

app/views/restaurants/crop.html.erb
<div class="container-fluid restaurant_form">

  <h1> Crop Profile Picture</h1>
    <div class="col-lg-10"></div>
      <%= simple_form_for @restaurant do |f| %>
        <%= f.submit "Save", class: "btn btn-default pull-right" %>
        <%= link_to "Back", edit_restaurant_path(f), class: "btn btn-default, pull-right" %>
        <%= f.cropbox :avatar %>
        <%= f.crop_preview :avatar %>
      <% end %> 
    </div>       
</div>

app/views/restaurants/edit.html.erb
<%= render "form" %>   

app/views/restaurants/index.html.erb
<div class="container-fluid restaurant_index">


  <div id="featured_restaurants" class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
  <h2>FEATURED RESTAURANTS</h2>
      <%= link_to (image_tag("http://elitedraperies.ca/wp-content/uploads/2013/08/hys-steakhouse-ottawa-logo.jpg", class: "center-block fr", width: "100%")), "#" %>
      <br>
        <%= link_to (image_tag("http://www.nuba.ca/wp-content/uploads/2012/11/nuba_gastwown_header.jpg", class: "center-block fr", width: "100%")), "#" %>
      <br>
        <%= link_to (image_tag("http://carileee.files.wordpress.com/2011/09/img_5177.jpg", class: "center-block fr", width: "100%")), "#" %>
  </div>

  <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 pull-right">
    <div class="panel-body">
      <h5 class="pull-right">Are you a restaurant owner?</h5>
        <br>
        <br>
        <p><%= link_to "Create Restaurant Profile", new_restaurant_path, class: "btn btn-default pull-right restaurant-profile-button" %></p>
    </div>


      <table class="table">
        <tr>
          <th><%= sortable "name" %></th>
          <th><%= sortable "address" %></th>
          <th><%= sortable "cuisine" %></th>
        </tr>
          <%= render partial: "page", locals: {r: @restaurant} %>
  </div>
</div>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  
  <div class="error-messages">
    <h2><%=pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
    
    <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  
  </div>
<% end %>

<%= render "form" %>

app/views/restaurants/show.html.erb
<ol class="breadcrumb">
  <li><a><%= link_to "Home", root_path %></a></li>
  <li><a><%= link_to "Restaurants", restaurants_path %></a></li>
  <li class="active"> <%= "#{@restaurant.name}" %></li>
</ol>


<div class="locations_page">

  <div class="container-fluid">

    <h1>
      <!-- Go to www.addthis.com/dashboard to customize your tools -->
      <div class="addthis_sharing_toolbox pull-right"><a href="http://www.opentable.com"><%= image_tag("OpenTable.jpg", width: "105", height: "50") %></a></div>

      <% if @restaurant.avatar.present? %>
          <%= image_tag @restaurant.avatar.url(:medium), id: "avatar"%>
          <%= "#{@restaurant.name}" %>
      <% else %>
          <%= "#{@restaurant.name}" %>
      <% end %>   
    </h1>



    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
      <table class="table table-responsive">
        <h2 class="restaurant_wine_listing"></h2>
        <tr>
          <th> Name </th>
          <th> Origin </th>
          <th> Type </th>
        </tr>
        <% @restaurant.wines.each do |w| %>
        <tr>
          <td><%= w.name %></td>
          <td><%= w.origin %></td>
          <td><%= w.kind %></td>
        </tr>
        <% end %>
      </table>
    </div>
 

    <div class="resto_profile resto_profile_well well col-xs-12 col-sm-12 col-md-4 col-lg-4 pull-right">
        <p>
        
          <td>
            <% if current_user == @restaurant.user %>
              <%= link_to "Delete", restaurant_path, method: :delete, class: "btn btn-default pull-right" %>
              <%= link_to "Edit", edit_restaurant_path(@restaurant), class: "btn btn-default pull-right" %>
            <% end %>
          </td>
        </p>
        <h6 class="resto_profile">
          <td><i class="fa fa-map-marker"></i> <%= "#{@restaurant.address}" %>
        </h6> 
        <h6 class="resto_profile">
          <td><i class="fa fa-cutlery"></i> <%= @restaurant.cuisine %></td>
        </h6>
      <div class:"center-block">
        <div id="map" style='width: 100%; height: 300px;'></div>
      </div>
      <br>
      <h2>Nearby Restaurants</h2>
      <div class="nearby_restos">
        <ul>
          <% for restaurant in @restaurant.nearbys(6) %>
          <div>
            <li><%= restaurant.name %> | <%= link_to restaurant.address, restaurant %></li>
          </div>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="well well col-xs-12 col-sm-12 col-md-8 col-lg-8" id="missing_wine_form">
      <h6>Are we missing something?  Let us know here</h6>
      <%= form_for [@restaurant, @wine] do |w| %>
        <div>
          <%= w.label :name %><br>
          <%= w.text_field :name, class: "form-control", placeholder: "Example: Chateau Montelena Estate Cabernet Sauvignon" %>
        </div>
        <div>
          <%= w.label :kind %><br>
          <%= w.text_field :kind, class: "form-control", placeholder: "Is it Red, White, Rose, or Champs?" %>
        </div>
        <div>
          <%= w.label :origin %><br>
          <%= w.text_field :origin, class: "form-control", placeholder: "Example: Napa Valley, USA" %>
        </div>
        <div>
          <%= w.label :serving_type %><br>
          <%= w.text_field :serving_type, class: "form-control", placeholder: "Is it offered as a glass, half bottle, or bottle?" %>
        </div>
        <br>
        <div>
          <%= w.submit "Save", class: "btn btn-default pull-right" %>
        </div>
        <br>
        <br>
      <% end %>
    </div>
    
  </div>
</div>

</section>

  <script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(13)
  });
  </script>

  <!-- Go to www.addthis.com/dashboard to customize your tools -->
  <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53af382b4ee31991"></script>