config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :wines do
    member do
      get :restaurants
    end
  end

  resources :restaurants do
    resources :wines, controller: 'restaurants_wines'
  end

  root "home#index"
  

end

app/models/wine.rb
class Wine < ActiveRecord::Base

  has_many :offerings

  has_many :restaurants, through: :offerings

  validates :name, :origin, presence: {message: "must exist"}
  validates_uniqueness_of :name, :scope => :kind

  self.per_page = 15

  def self.accessible_attributes
    ["name", "kind", "origin", "serving_type"]
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true, col_sep: "\t") do |row, index|
      wine = find_by_id(row[index]) || new
      wine.attributes = row.to_hash.slice(*accessible_attributes)
      wine.save!
      #wine = Wine.create! row.to_hash
      # wine.restaurants << restaurant
    end
  end

  def self.search(query)
    where("LOWER(name) like ?", "%#{query}%")
  end

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_wine, only: [:show, :restaurants]

  helper_method :sort_column, :sort_direction

  def new
    @wine = Wine.new
  end

  def create
    @wine = Wine.new(wine_params)
    # @wine.user = current_user
    if @wine.save
      redirect_to root_path, notice: "#{@wine.name} was added to the database"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @wine.update_attributes
      redirect_to wines_path
    else
      render :edit
    end
  end

  def show
  end

  def restaurants 
    @wine.restaurants.any?
  end

  def index
    if params[:search]
      @wines_search = Wine.search(params[:search]).paginate(:page => params[:page])
                                                  .order("#{sort_column} " "#{sort_direction}")

                                                  
    else
      @wines_search = Wine.paginate(:page => params[:page])
                          .order("#{sort_column} " "#{sort_direction}")
    end
    respond_to do |format|
      format.html
      format.js { render }
    end
  end

  def destroy
    @wine.destroy 
  end

  def import
    Wine.import(params[:file])
    redirect_to root_path, notice: "Wines imported"
  end

  private

  def wine_params
    params.require(:wine).permit(:name, :kind, :origin, :serving_type)
  end

  def find_wine
    @wine = Wine.find params[:id]
  end

  def sort_column
    Wine.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_paginate.html.erb
<% @wines_search.each do |w| %>
  <tr>
    <td>
      <%= link_to "#{w.name}", restaurants_wine_path(w) %>
    </td>
    <td>
    <%= w.origin %>
    </td>
    <td>
      <%= w.kind %>
    </td>
  </tr>
  <% end %>
</table>
<div class="text-center">
  <%= will_paginate @wines_search, :page_links => false %>
</div>
</div>
</div>

app/views/wines/index.html.erb
<div class="container-fluid wine_index">
  <div class="panel-body ">
    <h5 class="pull-right">Want to Add Wines to Your Restaurant?</h5>
      <br>
      <br>
      <p><%= link_to "Create Restaurant Profile", new_restaurant_path, class: "btn btn-default pull-right restaurant-profile-button" %></p>
  </div>

  <h1>WINE INDEX</h1>
  <div class="col-xs-6 col-sm-4 col-md-4">
    <%= image_tag("kc.jpg", class: "center-block fw", width: "100%") %>
  </div>
  
  <div class="col-xs-6 col-sm-4 col-md-4">
    <%= image_tag("lynnfalconer.jpg", class: "center-block fw", width: "100%") %>
  </div>

  <div class="hidden-xs col-sm-4 col-md-4">
    <%= image_tag("burrowing-owl.jpg", class: "center-block fw", width: "100%") %>
  </div>

  <table class="table">
    <tr>
      <th><%= sortable "name" %></th>
      <th><%= sortable "origin" %></th>
      <th><%= sortable "kind", "Type" %></th>
    </tr>
      <%= render partial: "paginate", locals: {object: @wines_search} %>

  </div>
</div>

<!-- <h2>Import Wines</h2> -->

<%#= form_tag import_wines_path, multipart: true do %>
  <%#= file_field_tag :file %>
  <%#= submit_tag "Import" %>
<%# end %>

app/views/wines/restaurants.html.erb
<ol class="breadcrumb">
  <li><a><%= link_to "Home", root_path %></a></li>
  <li><a><%= link_to "Wines", wines_path %></a></li>
  <li class="active"><%= "#{@wine.name}" %></li>
</ol>


<div class="container-fluid search_results">

  <% @wine.restaurants.each do |restaurant| %>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
      <div id="search_results">
        <%= link_to image_tag(restaurant.avatar.url(:medium), class: "img-responsive"), restaurant_path(restaurant) %>  
      </div>
    </div>
  <% end %>
</div>