config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :wines do
    member do
      get :restaurants
    end
  end

  resources :restaurants do
    resources :wines, controller: 'restaurants_wines'
  end

  root "home#index"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vinapp | Wine Search</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:400,700|Open+Sans:400,700,600' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>

  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "V<span>i</span>NAPP".html_safe, root_path, class: "navbar-brand" %>
      </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Wines", wines_path %></li>
        <li><%= link_to "Restaurants", restaurants_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %><li>
          <li><%= link_to "Profile", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Create Account", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav> 

<body id="background-image">


  <%= yield %>
  
</body>

</html>